Fixed Directory Traversal Issue in unzipTo and added tests
pathikrit/better-files pull request #633
Opened 2023-09-26 23:24 UTC by sandumjacob

2023-09-27 13:21 UTC, pathikrit requested changes

2023-09-27 13:21 UTC, pathikrit commented on src/main/scala/better/files/File.scala
> +    println(entryCanonicalPath)
rm println

2023-09-29 13:26 UTC, pathikrit approved these changes

2023-09-29 13:27 UTC, merged

2023-09-29 18:01 UTC, sandumjacob commented
I believe some build tests for MacOS are failing because the unsafe unzip test tries to unzip a directory traversal ZIP file, which causes a file access exception